# Generated by Django 4.1.4 on 2023-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww.theaxebraughing.uk%2F%3Fattachment_id%3D2665&psig=AOvVaw2BGeXRnY0wqRGDa2NBWFqp&ust=1687261979078000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCNCxquqiz_8CFQAAAAAdAAAAABAJ', max_length=500),
        ),
    ]
