# Generated by Django 4.2.2 on 2023-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://members.jusbfit247.com/wp-content/uploads/food-placeholder.jpg', max_length=500),
        ),
    ]
